const data = [
  // 🔹 MEN'S COLLECTION
  {
    title: "Men's Classic White Shirt",
    description:
      "A stylish and comfortable white cotton shirt, perfect for casual and formal wear.",
    image: {
      filename: "mens-shirt",
      url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 39.99,
    size: ["S", "M", "L", "XL"],
    color: ["White", "Blue", "Black"],
    category: "Men",
    type: "Topwear",
    tags: ["Formal", "Casual", "Cotton"],
    inStock: true,
  },
  {
    title: "Men's Casual T-Shirt",
    description:
      "A cool and breathable cotton t-shirt, ideal for everyday wear.",
    image: {
      filename: "mens-tshirt",
      url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 19.99,
    size: ["S", "M", "L", "XL"],
    color: ["Red", "Green", "Gray"],
    category: "Men",
    type: "Topwear",
    tags: ["Casual", "Cotton", "Trendy"],
    inStock: true,
  },
  {
    title: "Men's Denim Jeans",
    description: "Classic slim-fit denim jeans for a stylish everyday look.",
    image: {
      filename: "mens-jeans",
      url: "https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 49.99,
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    category: "Men",
    type: "Bottomwear",
    tags: ["Denim", "Slim Fit", "Trendy"],
    inStock: true,
  },
  {
    title: "Men's Joggers",
    description: "Comfortable joggers for sports and casual wear.",
    image: {
      filename: "mens-joggers",
      url: "https://images.unsplash.com/photo-1604176354204-9268737828e4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 34.99,
    size: ["M", "L", "XL"],
    color: ["Black", "Gray"],
    category: "Men",
    type: "Bottomwear",
    tags: ["Athleisure", "Comfort"],
    inStock: true,
  },
  {
    title: "Men's Winter Jacket",
    description: "A warm and stylish winter jacket with fur lining.",
    image: {
      filename: "mens-jacket",
      url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 89.99,
    size: ["L", "XL"],
    color: ["Black", "Brown"],
    category: "Men",
    type: "Winterwear",
    tags: ["Winter", "Cozy"],
    inStock: false,
  },
  {
    title: "Men's Woolen Sweater",
    description: "A cozy and soft woolen sweater to keep you warm.",
    image: {
      filename: "mens-sweater",
      url: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 59.99,
    size: ["M", "L"],
    color: ["Navy", "Gray"],
    category: "Men",
    type: "Winterwear",
    tags: ["Winter", "Comfort"],
    inStock: true,
  },

  // 🔹 WOMEN'S COLLECTION
  {
    title: "Women's Summer Floral Dress",
    description: "A lightweight and breathable floral dress.",
    image: {
      filename: "womens-dress",
      url: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 59.99,
    size: ["S", "M", "L"],
    color: ["Yellow", "Pink", "White"],
    category: "Women",
    type: "Topwear",
    tags: ["Floral", "Casual"],
    inStock: true,
  },
  {
    title: "Women's Crop Top",
    description: "A stylish crop top for casual wear.",
    image: {
      filename: "womens-crop",
      url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 29.99,
    size: ["S", "M"],
    color: ["Black", "White"],
    category: "Women",
    type: "Topwear",
    tags: ["Trendy", "Casual"],
    inStock: true,
  },
  {
    title: "Women's High Waist Jeans",
    description: "Trendy high-waist skinny jeans.",
    image: {
      filename: "womens-jeans",
      url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 69.99,
    size: ["S", "M", "L"],
    color: ["Blue", "Black"],
    category: "Women",
    type: "Bottomwear",
    tags: ["Denim", "Fashionable"],
    inStock: true,
  },
  {
    title: "Women's Leggings",
    description: "Comfortable and stylish leggings.",
    image: {
      filename: "womens-leggings",
      url: "https://images.unsplash.com/photo-1588117305388-c2631a279f82?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 34.99,
    size: ["M", "L"],
    color: ["Black", "Gray"],
    category: "Women",
    type: "Bottomwear",
    tags: ["Athleisure", "Casual"],
    inStock: true,
  },
  {
    title: "Women's Woolen Coat",
    description: "A warm woolen coat for winter.",
    image: {
      filename: "womens-coat",
      url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 99.99,
    size: ["M", "L"],
    color: ["Red", "Beige", "Black"],
    category: "Women",
    type: "Winterwear",
    tags: ["Winter", "Elegant"],
    inStock: true,
  },
  {
    title: "Women's Puffer Jacket",
    description: "A stylish and cozy puffer jacket.",
    image: {
      filename: "womens-jacket",
      url: "https://images.unsplash.com/photo-1551232864-3f0890e580d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 79.99,
    size: ["S", "M"],
    color: ["Blue", "Pink"],
    category: "Women",
    type: "Winterwear",
    tags: ["Winter", "Trendy"],
    inStock: false,
  },

  // 🔹 KIDS' COLLECTION
  {
    title: "Kids' Cartoon T-Shirt",
    description: "A cute cotton t-shirt with cartoon prints.",
    image: {
      filename: "kids-tshirt",
      url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 19.99,
    size: ["XS", "S"],
    color: ["Blue", "Red"],
    category: "Kids",
    type: "Topwear",
    tags: ["Cartoon", "Casual"],
    inStock: true,
  },
  {
    title: "Kids' Denim Shorts",
    description: "Stylish denim shorts for kids.",
    image: {
      filename: "kids-shorts",
      url: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 24.99,
    size: ["XS", "S"],
    color: ["Blue", "Black"],
    category: "Kids",
    type: "Bottomwear",
    tags: ["Denim", "Comfort"],
    inStock: true,
  },
  {
    title: "Kids' Hooded Jacket",
    description: "A warm winter jacket for kids.",
    image: {
      filename: "kids-jacket",
      url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
    },
    price: 49.99,
    size: ["S", "M"],
    color: ["Pink", "Blue"],
    category: "Kids",
    type: "Winterwear",
    tags: ["Winter", "Cozy"],
    inStock: false,
  },
];

// Overwrite and export with IDs
export const sampleDresses = data.map((item) => ({
  ...item,
  id: crypto.randomUUID(),
}));
